### ISSUE TITLE
Followed the instruction and looked at the example but it's still not working

### ISSUE THREAD

**Issue by richardsondx** [keensoft/FullScreenImage-Cordova-Plugin#12]
My environment is Phonegap ( 4.2.0-0.23.0 )  + AngularJS  

I put this in my controller:

    $scope.toggleFullscreen = function(imageSrc){

      FullScreenImage.showImageURL(imageSrc);
   
    };

but it failed and returned:
ReferenceError: Can't find variable: FullScreenImage

    $scope.toggleFullscreen = function(imageSrc){
      window.FullScreenImage.showImageURL(imageSrc);      
    };:

returned:
Error: undefined is not an object (evaluating 'window.FullScreenImage.showImageURL')

On my view I am calling it as follow:
<img ng-click="toggleFullscreen(artwork.image)" ng-src="{{artwork.image}}"

**Comment by slaptot** [comment]
Hi @richardsondx ,
your problem sounds like you are not using phonegap propertly or your app is not including the plugin. Have you try to compile iOS or Android app? Have you check "cordova plugin list" shows FullScreenImage plugin?
Please let me know your progress.

**Comment by slaptot** [comment]
@richardsondx did you try it? let me know ;)
