### ISSUE TITLE
Saving image to system photo album or gallery

### ISSUE THREAD

**Issue by mbz6200** [keensoft/FullScreenImage-Cordova-Plugin#14]
Is there any way to save displayed image to the phone's photo album or gallery using this plug-in?

**Comment by slaptot** [comment]
Hi @mbz6200 ,
plugin open native view for display views. iOS plugin (UIDocumentInteractionController) let you share, save, print... if you open menu on top right. Android, open it with your viewer selection, so if the viewer can save it, you can :).
