### ISSUE TITLE
Opening image on remote url ?

### ISSUE THREAD

**Issue by tahola** [keensoft/FullScreenImage-Cordova-Plugin#15]
Hello, I am using this plugin with an hybrid / remote app so I would like to know if its possible by any way to opening image stored on remote (not inside www).
Thanks for your work.

**Comment by slaptot** [comment]
Hi @tahola,
nowadays the plugin allows to open images from devices and open Base64 images. In your case, an approach could be convert remote images to Base64 and then show it. Any way I´ll keep in mind.

**Comment by jaredgreener** [comment]
Try this:

function convertImgToBase64URL(url, callback, outputFormat){
    var canvas = document.createElement('CANVAS'),
        ctx = canvas.getContext('2d'),
        img = new Image;
    img.crossOrigin = 'Anonymous';
    img.onload = function(){
        var dataURL;
        canvas.height = img.height;
        canvas.width = img.width;
        ctx.drawImage(img, 0, 0);
        dataURL = canvas.toDataURL(outputFormat);
        console.log("loaded base64");
        callback.call(this, dataURL);
        canvas = null; 
    };
    img.src = url;
}

function loadImageViewer(link, title){
	
	console.log("0");
	
	convertImgToBase64URL(link, function(base64String) {

		console.log("1 " + link + " : " + title);
		clearOverlay();
		FullScreenImage.showImageBase64(base64String, title);
		console.log(base64String);
	});
	
}

**Comment by vivekaroli** [comment]
clearOverlay();

breaks the script what to do?
