### ISSUE TITLE
New updates break iOS

### ISSUE THREAD

**Issue by jaredgreener** [keensoft/FullScreenImage-Cordova-Plugin#16]
I just updated to the latest repo and it broke my iOS implementation... nothing else changed on my end. Any ideas?

I even loaded the example -- and none of the images loaded

**Comment by slaptot** [comment]
@jaredgreener could you please show your Xcode logs, errors... Are you testing with real device? Simulator? 
Example code is working fine in my simulators and iPhone 4s ios 8.3 :)

**Comment by jaredgreener** [comment]
It doesn't throw any errors -- it fails silently. I ended up replacing the block inside showBase64() with the code from the previous version and it worked. When I get a second Ill reset and send you more info.

**Comment by sdhintGIT** [comment]
same issue for me, is there any work around to get this on iOS? sending in the base64 string, it opens the viewer, but just shows loading....

**Comment by sdhintGIT** [comment]
found that i wasn't stripping off the data part of the string, once done it loads up on iOS as expected.

 var imagestrip = imgStr.replace(/^data:image\/(png|jpeg|jpg);base64,/, "");

**Comment by slaptot** [comment]
Yes, that's why we think in mobile and base64 must be without header

**Comment by jaredgreener** [comment]
Still doesn't solve my issue...

 My viewer doesn't open at all and fails silently

**Comment by slaptot** [comment]
@Jaredgreener could you please open a github with your code or simplify code of it? I'll be pleased to help you

**Comment by jaredgreener** [comment]
I finally solved my problem -- it was because I had implemented some callback functions using the previous version and you added another variable in the function parameters in the new version. I have updated my code -- can you give me permission to upload a branch and I will create a pull request with callbacks implemented into iOS. This is helpful so you can display a loading spinner while the image is loading (especially if it is being downloaded like I am) and then hide spinner on success / show error message on failure.

Thanks!

**Comment by slaptot** [comment]
Sure, please make a pull request with your changes on master

**Comment by jaredgreener** [comment]
It says I don't have permission...

**Comment by slaptot** [comment]
Hi @jaredgreener,
https://help.github.com/articles/using-pull-requests/ here explain how to proceed

**Comment by slaptot** [comment]
Hi @jaredgreener,
I just approve a pull request, please do it again. Your changes are very useful :)
