### ISSUE TITLE
full screen image is not working

### ISSUE THREAD

**Issue by chaithanya123** [keensoft/FullScreenImage-Cordova-Plugin#2]
$scope.getPhoto = function () {
    Camera.getPicture().then(function (imageURI) {
      console.log(imageURI);
      $scope.lastPhoto = imageURI;
      $scope.fullscreen=function(){
      console.log('fullscreen clicked');
    FullScreenImage.showImageURL($scope.lastPhoto);
  console.log('fullscreen photo'+ $scope.lastPhoto);
    };
  }
}

 button ng-click="getPhoto()" class="button button-block button-primary" Take Photo</button>
    img ng-src="{{lastPhoto}}" style="max-width:50%" ng-click="fullscreen()"
In html side is
 

anyone help me guys

**Comment by dimanchee** [comment]
It is not working in iOS 8.1.2.

**Comment by dimanchee** [comment]
Sorry it is working well. I missed reading the description. I was using image base64 but the part is only accept under /www/. Can you please update to make it work with image base64? Thanks!

**Comment by dutscher** [comment]
+1 for dimanchee

**Comment by BBosman** [comment]
+1 for dimanchee

I would love to be able to use this plugin to show base64 encoded images fullscreen.

**Comment by slaptot** [comment]
Please check this branch https://github.com/keensoft/FullScreenImage-Cordova-Plugin/tree/base64-support 

We have create iOS base64 fullscreen and soon we create it for Android devices. We provided an example also.

**Comment by slaptot** [comment]
Merged! Please let me know if it works fine ;)
