### ISSUE TITLE
[object Object] has no method 'showImageBase64'

### ISSUE THREAD

**Issue by madvas** [keensoft/FullScreenImage-Cordova-Plugin#21]
When added via `cordova plugin add es.keensoft.fullscreenimage` , this method is missing.
When added via `cordova plugin add https://github.com/keensoft/FullScreenImage-Cordova-Plugin.git` , `showImageBase64` method is there

**Comment by Tim-W** [comment]
+1

**Comment by phoue** [comment]
+1

**Comment by carsonip** [comment]
It appears to me that the developer does not update the plugin in the Cordova Plugin Registry. It would be great if the plugin in the registry is up-to-date and the version number reflects changes in it.

**Comment by slaptot** [comment]
Hi,
I just update plugin.xml to version 1.0.1. I hope http://plugins.cordova.io/#/package/es.keensoft.fullscreenimage will update automatically as soon as posible

**Comment by carsonip** [comment]
Cordova plugins registry (CPR) is now read only so nothing will be updated. Please consider moving the plugin to the npm ecosystem.

[Here](https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html) is the guide. Thanks @slaptot.

**Comment by slaptot** [comment]
Hi @carsonip,
I'm waiting a merge into Cordova-plugin-registry. https://github.com/stevengill/cordova-registry-mapper/pull/57
