### ISSUE TITLE
showImageBase64 faild when view a large image

### ISSUE THREAD

**Issue by lonestonewy** [keensoft/FullScreenImage-Cordova-Plugin#22]
It seems that NSURL retrieve a large base64 string will return nill, and then write file failed.

I suggested that decode base64 string directly and write file to caches directory.

**Comment by lonestonewy** [comment]
//        NSString *str = [NSString stringWithFormat:@"data:image/%@;base64,",imageType];
//        str = [str stringByAppendingString:fullPath];
//        NSURL *url = [NSURL URLWithString:str];
        NSData *imageData = [NSData dataFromBase64String:fullPath];
        UIImage *ret = [UIImage imageWithData:imageData];

solved the problem;

**Comment by slaptot** [comment]
Thanks @lonestonewy useful info, will be merged as soon as posible.
