### ISSUE TITLE
Android store temp image to cache directory instead of root in external storage

### ISSUE THREAD

**Issue by carsonip** [keensoft/FullScreenImage-Cordova-Plugin#23]
Currently the temporary image copied from the app side to `output.jpg` (or other file extension) under the device's external storage's root. Such a temporary file may appear under some gallery apps which search for images throughout the storage, which is not desirable.

**Comment by slaptot** [comment]
Hi @carsonip,
could you please send me pull request with your proposal?
Thanks in advance

**Comment by carsonip** [comment]
Hi @slaptot, I am currently working on it. PR will be there soon.
