### ISSUE TITLE
rotation

### ISSUE THREAD

**Issue by Hirbod** [keensoft/FullScreenImage-Cordova-Plugin#7]
Hi,

I've set up my app for Portrait-Mode only, but the Viewer allows rotation. If I rotate to landscape and close the documentView, my whole app is broken. The only chance to fix the view is to open again, rotate to landscape and back, then close.

Is there any any way to prevent rotation? (or detect allowed rotation).

Thanks!

**Comment by Hirbod** [comment]
Any news on this?

**Comment by slaptot** [comment]
May be we can decide how presentation view should be. In Example app, Ionic framework version do not rescale screen correctly, let me check

**Comment by Hirbod** [comment]
Thanks

**Comment by slaptot** [comment]
Hi @Hirbod ,
example its made with ionic framework and this framework create MainViewController. Here you can find "shouldAutorotateToInterfaceOrientation". If your app should handle multiple orientations, you should use in this way:

- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
{
return YES; //for supported orientations
//return [super shouldAutorotateToInterfaceOrientation:interfaceOrientation];
}

Any way I´ll update example as soon as possible.
