### ISSUE TITLE
Error compiling App 

### ISSUE THREAD

**Issue by danicastanos** [keensoft/FullScreenImage-Cordova-Plugin#9]
An error is occurring since yesterday when I try to compile my App using your plugin, added using the git URL: cordova plugin add https://github.com/keensoft/FullScreenImage-Cordova-Plugin.git

The error is not happening when I add the plugin via de cordova plugins repo: cordova plugin add es.keensoft.fullscreenimage (But this version does not include FullScreenImage.showImageBase64 method)

Maybe something is wrong since your last commits

Plugins/es.keensoft.fullscreenimage/FullScreenImage.m:17:14: Property 'docInteractionController' not found on object of type 'FullScreenImage *'
Plugins/es.keensoft.fullscreenimage/FullScreenImage.m:19:14: Property 'docInteractionController' not found on object of type 'FullScreenImage *'
Plugins/es.keensoft.fullscreenimage/FullScreenImage.m:20:14: Property 'docInteractionController' not found on object of type 'FullScreenImage *'
Plugins/es.keensoft.fullscreenimage/FullScreenImage.m:24:14: Property 'docInteractionController' not found on object of type 'FullScreenImage *'
Plugins/es.keensoft.fullscreenimage/FullScreenImage.m:32:14: Property 'documentURLs' not found on object of type 'FullScreenImage *'
Plugins/es.keensoft.fullscreenimage/FullScreenImage.m:42:19: Property 'documentURLs' not found on object of type 'FullScreenImage *'
Plugins/es.keensoft.fullscreenimage/FullScreenImage.m:47:23: Property 'docInteractionController' not found on object of type 'FullScreenImage *'
Plugins/es.keensoft.fullscreenimage/FullScreenImage.m:69:67: Invalid conversion specifier ';'
Plugins/es.keensoft.fullscreenimage/FullScreenImage.m:92:19: Property 'documentURLs' not found on object of type 'FullScreenImage *'
Plugins/es.keensoft.fullscreenimage/FullScreenImage.m:97:23: Property 'docInteractionController' not found on object of type 'FullScreenImage *'

**Comment by slaptot** [comment]
Commit merged! Try it now ;)

**Comment by danicastanos** [comment]
Mmmmm... I can compile the App now, but the plugin is still not working.
When I call: window.FullScreenImage.showImageBase64( base64Data ,filename, null );

Nothing seems to happen. No error on JS console, no error on Xcode console... Yesterday same code was working...

**Comment by danicastanos** [comment]
Well, I can add more information by now.
In the previous version of the plugin, the type parameter was not needed for me, I always sent null, and the image was displayed properly.

In this version, without this parameter, nothing seems to happen, but when I fill it, the plugin in fact opens, but it gets stuck with the loading View. For a jpeg file, I've tried using: jpg, jpeg, image/jpeg

Hope it helps.

**Comment by danicastanos** [comment]
I think this is the problem:

Url is not well formet. ImageType is not being replace.

![screen shot 2015-02-26 at 13 40 50](https://cloud.githubusercontent.com/assets/11208134/6392084/46298338-bdbd-11e4-8476-3d815e8e7a83.png)

**Comment by slaptot** [comment]
Please check this branch https://github.com/keensoft/FullScreenImage-Cordova-Plugin/tree/getContentType

**Comment by danicastanos** [comment]
Now it works... But there's still a bug on this line:

if([imageType isKindOfClass:[NSNull class]] || [imageName isEqualToString:@""]){
            imageName = @"default";
        }

imageType must be replaced by imageName

**Comment by slaptot** [comment]
Fast reviewer!! Thanks for you testing Job ;). Any way, aims you to take actively part on it, we are pleased to welcome someone who want to improve it.

**Comment by danicastanos** [comment]
Thank you for easing things and share it public!
